version: '3'

services:
  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4041:4041"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./data:/tmp/data

  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8081:8081"
    volumes:
      - ./data:/tmp/data

  spark-worker-2:
    image: bde2020/spark-worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8082:8081"
    volumes:
      - ./data:/tmp/data

  spark-worker-3:
    image: bde2020/spark-worker
    container_name: spark-worker-3
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8083:8081"
    volumes:
      - ./data:/tmp/data

  spark-worker-4:
    image: bde2020/spark-worker
    container_name: spark-worker-4
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8084:8081"
    volumes:
      - ./data:/tmp/data